/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteRouteImport } from './routes/_session/route'
import { Route as HomeRouteRouteImport } from './routes/_home/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as SessionSignUpRouteImport } from './routes/_session/sign-up'
import { Route as SessionSignInRouteImport } from './routes/_session/sign-in'
import { Route as HomeAboutRouteImport } from './routes/_home/about'

const SessionRouteRoute = SessionRouteRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)
const SessionSignUpRoute = SessionSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => SessionRouteRoute,
} as any)
const SessionSignInRoute = SessionSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => SessionRouteRoute,
} as any)
const HomeAboutRoute = HomeAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => HomeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof HomeAboutRoute
  '/sign-in': typeof SessionSignInRoute
  '/sign-up': typeof SessionSignUpRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof HomeAboutRoute
  '/sign-in': typeof SessionSignInRoute
  '/sign-up': typeof SessionSignUpRoute
  '/': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_home': typeof HomeRouteRouteWithChildren
  '/_session': typeof SessionRouteRouteWithChildren
  '/_home/about': typeof HomeAboutRoute
  '/_session/sign-in': typeof SessionSignInRoute
  '/_session/sign-up': typeof SessionSignUpRoute
  '/_home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/sign-in' | '/sign-up' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/sign-in' | '/sign-up' | '/'
  id:
    | '__root__'
    | '/_home'
    | '/_session'
    | '/_home/about'
    | '/_session/sign-in'
    | '/_session/sign-up'
    | '/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  SessionRouteRoute: typeof SessionRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SessionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRouteRoute
    }
    '/_session/sign-up': {
      id: '/_session/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SessionSignUpRouteImport
      parentRoute: typeof SessionRouteRoute
    }
    '/_session/sign-in': {
      id: '/_session/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SessionSignInRouteImport
      parentRoute: typeof SessionRouteRoute
    }
    '/_home/about': {
      id: '/_home/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof HomeAboutRouteImport
      parentRoute: typeof HomeRouteRoute
    }
  }
}

interface HomeRouteRouteChildren {
  HomeAboutRoute: typeof HomeAboutRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeAboutRoute: HomeAboutRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface SessionRouteRouteChildren {
  SessionSignInRoute: typeof SessionSignInRoute
  SessionSignUpRoute: typeof SessionSignUpRoute
}

const SessionRouteRouteChildren: SessionRouteRouteChildren = {
  SessionSignInRoute: SessionSignInRoute,
  SessionSignUpRoute: SessionSignUpRoute,
}

const SessionRouteRouteWithChildren = SessionRouteRoute._addFileChildren(
  SessionRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  HomeRouteRoute: HomeRouteRouteWithChildren,
  SessionRouteRoute: SessionRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
